config/routes.rb
Rails.application.routes.draw do

  resources :tutors do 
    resources :ranks
  end

  root "tutors#index"

  get "/aranks" => "ranks#aranks"

end

app/models/rank.rb
class Rank < ActiveRecord::Base
  belongs_to :tutor
  validates :rating, :review, presence: true
  validates :rating, numericality: {
  	greater_than_or_equal_to: 1,
  	less_than_or_equal_to: 5
  }
end

app/models/tutor.rb
class Tutor < ActiveRecord::Base
	has_many :ranks, dependent: :delete_all
	validates :name, presence: true

	def ratingAverage
		if self.ranks.blank?
			ratingAverage = 0
		else
			self.ranks.average(:rating).round(2)
		end
	end
	Age = %w(20-30 30-40 40-50 50+)
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ranks_controller.rb
class RanksController < ApplicationController
  before_action :set_tutor, except: [:aranks]
  before_action :set_rank, only: [:show, :edit, :update, :destroy]

  # GET /ranks
  # GET /ranks.json
  def aranks
    @aranks = Rank.all
  end

  def index
    @ranks = @tutor.ranks.all.order("created_at DESC")
  end

  # GET /ranks/1
  # GET /ranks/1.json
  def show
  end

  # GET /ranks/new
  def new
    @rank = @tutor.ranks.build()
  end

  # GET /ranks/1/edit
  def edit
  end

  # POST /ranks
  # POST /ranks.json
  def create
    @rank = @tutor.ranks.build(rank_params)

    respond_to do |format|
      if @rank.save
        format.html { redirect_to [@tutor, @rank], notice: 'Rank was successfully created.' }
        format.json { render :show, status: :created, location: @rank }
      else
        format.html { render :new }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ranks/1
  # PATCH/PUT /ranks/1.json
  def update
    respond_to do |format|
      if @rank.update(rank_params)
        format.html { redirect_to [@tutor, @rank], notice: 'Rank was successfully updated.' }
        format.json { render :show, status: :ok, location: @rank }
      else
        format.html { render :edit }
        format.json { render json: @rank.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ranks/1
  # DELETE /ranks/1.json
  def destroy
    @rank.destroy
    respond_to do |format|
      format.html { redirect_to tutor_ranks_url, notice: 'Rank was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_tutor
      @tutor = Tutor.find(params[:tutor_id])
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_rank
      @rank= @tutor.ranks.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rank_params
      params.require(:rank).permit(:rating, :review)
    end
end

app/controllers/tutors_controller.rb
class TutorsController < ApplicationController
  before_action :set_tutor, only: [:show, :edit, :update, :destroy]

  # GET /tutors
  # GET /tutors.json
  def index
    @tutors = Tutor.all
  end

  # GET /tutors/1
  # GET /tutors/1.json
  def show
  end

  # GET /tutors/new
  def new
    @tutor = Tutor.new
  end

  # GET /tutors/1/edit
  def edit
  end

  # POST /tutors
  # POST /tutors.json
  def create
    @tutor = Tutor.new(tutor_params)

    respond_to do |format|
      if @tutor.save
        format.html { redirect_to @tutor, notice: 'Tutor was successfully created.' }
        format.json { render :show, status: :created, location: @tutor }
      else
        format.html { render :new }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tutors/1
  # PATCH/PUT /tutors/1.json
  def update
    respond_to do |format|
      if @tutor.update(tutor_params)
        format.html { redirect_to @tutor, notice: 'Tutor was successfully updated.' }
        format.json { render :show, status: :ok, location: @tutor }
      else
        format.html { render :edit }
        format.json { render json: @tutor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tutors/1
  # DELETE /tutors/1.json
  def destroy
    @tutor.destroy
    respond_to do |format|
      format.html { redirect_to tutors_url, notice: 'Tutor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tutor
      @tutor = Tutor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tutor_params
      params.require(:tutor).permit(:name, :sex, :state, :lg, :age_range)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ranks_helper.rb
module RanksHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tutorsapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/ranks/_form.html.erb
<%= form_for([@tutor, @rank], html: {multipart: true}) do |f| %>
  <% if @rank.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rank.errors.count, "error") %> prohibited this rank from being saved:</h2>

      <ul>
      <% @rank.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div id = "star-rating"></div>
  </div>
  <div class="field">
    <%= f.label :review %><br>
    <%= f.text_area :review %>
  </div>
  <div class="field">
    <%= f.label :tutor_id %><br>
    <%= f.text_field :tutor_id %>
  </div>
  <div class="actions">
    <%= f.submit "Submit Review" %>
  </div>
<% end %>

<script>
  $('#star-rating').raty({
  starOn: '<%= image_path('star-on.png') %>',
  starOff: '<%= image_path('star-off.png') %>',
  starHalf: '<%= image_path('star-half.png') %>',
  path: '',
  scoreName: 'rank[rating]',
  space: true 
});
</script>

app/views/ranks/aranks.html.erb
<h1>All Reviews</h1>
<% @aranks.each do |rank| %>
	<p><%= rank.rating %></p>
	<p><%= rank.review %></p>
<% end %>

app/views/ranks/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', [@tutor, @rank] %> |
<%= link_to 'Back', tutor_ranks_path %>

app/views/ranks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Rating</th>
      <th>Review</th>
      <th>Tutor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ranks.each do |rank| %>
      <tr>
        <td class = "star-rating" data-score= <%= rank.rating %> ></td>
        <td><%= rank.review %></td>
        <td><%= rank.tutor.name %></td>
        <td><%= link_to 'Show', [@tutor, rank] %></td>
        <td><%= link_to 'Edit', [:edit, @tutor, rank] %></td>
        <td><%= link_to 'Destroy', [@tutor, rank], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Home', '/' %> |
<%= link_to 'New Review', new_tutor_rank_path(@tutor) %>

<script>
  $('.star-rating').raty({
      starOn: '<%= image_path('star-on.png') %>',
      starOff: '<%= image_path('star-off.png') %>',
      starHalf: '<%= image_path('star-half.png') %>',
      path: '',
      readOnly: true,
      score: function(){
          return $(this).attr('data-score');
        }
});
</script>

app/views/ranks/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', tutor_ranks_path(@tutor) %>

app/views/ranks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Rating:</strong>
  <div class = "reviews">
  	<div class="star-rating" data-score = <%= @rank.rating %> >
  	</div>
  </div>
</p>

<p>
  <strong>Review:</strong>
  <%= @rank.review %>
</p>

<p>
  <strong>Tutor:</strong>
  <%= @rank.tutor.name %>
</p>

<%= link_to 'Edit', [:edit, @tutor, @rank] %> |
<%= link_to 'Back', tutor_ranks_path(@tutor) %>

<script>
	$('.star-rating').raty({
		starOn: '<%= image_path('star-on.png') %>',
		starOff: '<%= image_path('star-off.png') %>',
		starHalf: '<%= image_path('star-half.png') %>',
		path: '',
		readOnly: true,
		score: function(){
			return $(this).attr('data-score');
		}

	});
</script>

app/views/tutors/_form.html.erb
<%= form_for(@tutor) do |f| %>
  <% if @tutor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tutor.errors.count, "error") %> prohibited this tutor from being saved:</h2>

      <ul>
      <% @tutor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :age_range %>
    <%= f.select :age_range, options_for_select(Tutor::Age, @tutor.age_range) %>
  </div>
  <div class="field">
    <%= f.label :sex %><br>
    <%= f.text_field :sex %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :lg %><br>
    <%= f.text_field :lg %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tutors/edit.html.erb
<h1>Editing Tutor</h1>

<%= render 'form' %>

<%= link_to 'Show', @tutor %> |
<%= link_to 'Back', tutors_path %>

app/views/tutors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tutors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Sex</th>
      <th>State</th>
      <th>Lg</th>
      <th>Age Range</th>
      <th>Rating</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tutors.each do |tutor| %>
      <tr>
        <td><%= tutor.name %></td>
        <td><%= tutor.sex %></td>
        <td><%= tutor.state %></td>
        <td><%= tutor.lg %></td>
        <td><%= tutor.age_range %></td>
        <td class = "star-rating" data-score = <%= tutor.ratingAverage %> ></td>
        <td><%= link_to 'Show', tutor %></td>
        <td><%= link_to 'Edit', edit_tutor_path(tutor) %></td>
        <td><%= link_to 'Destroy', tutor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tutor', new_tutor_path %>

<script>
  $('.star-rating').raty({
      starOn: '<%= image_path('star-on.png') %>',
      starOff: '<%= image_path('star-off.png') %>',
      starHalf: '<%= image_path('star-half.png') %>',
      path: '',
      readOnly: true,
      score: function(){
          return $(this).attr('data-score');
        }
});
</script>

app/views/tutors/new.html.erb
<h1>New Tutor</h1>

<%= render 'form' %>

<%= link_to 'Back', tutors_path %>

app/views/tutors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @tutor.name %>
</p>

<p>
  <strong>Sex:</strong>
  <%= @tutor.sex %>
</p>

<p>
  <strong>State:</strong>
  <%= @tutor.state %>
</p>
<p>
<strong>Age Range:</strong>
<%= @tutor.age_range %>
</p>
<p>
  <strong>Lg:</strong>
  <%= @tutor.lg %>
</p>
<%= link_to 'Edit', edit_tutor_path(@tutor) %> |
<%= link_to 'Back', tutors_path %> <br>
<br>
<% if @tutor.ranks.blank? %>
<%= link_to "Be the first, Add Review", new_tutor_rank_path(@tutor), class: "btn btn-success" %>
<% else %>
	<p><%= pluralize("#{@tutor.ranks.count}", "Review") %></p>
	<p class="star-rating" data-score= <%= @tutor.ratingAverage %> ></p>
	<hr>
	<% @tutor.ranks.each do |r| %>
		<div class = "reviews">
			<div class = "star-rating" data-score= <%= r.rating %> ></div>
		</div>
		<p><%= r.review %></p>
	<% end %>
<% end %>
<%= link_to 'Add Review', new_tutor_rank_path(@tutor) %>

<script>
	$('.star-rating').raty({
  		starOn: '<%= image_path('star-on.png') %>',
  		starOff: '<%= image_path('star-off.png') %>',
  		starHalf: '<%= image_path('star-half.png') %>',
		  path: '',
		  readOnly: true,
		  score: function(){
					return $(this).attr('data-score');
				}
});
</script>